### PR TITLE
Move urUSM into new file

### PR DESCRIPTION
**Pull request by bmyates**

### CODE REVIEW

**Comment by bmyates** [comment]
@jandres742  any objection to merging this?

**Comment by jandres742** [comment]
> @jandres742 any objection to merging this?

No, but https://github.com/jandres742/llvm/pull/9 introduced regressions in a test. I'm fixing it and then, once clear, will merge this.

https://github.com/intel/llvm/pull/8744/commits/592e0d0589cb4700240f792b9e6d9d387180027e

**Comment by jandres742** [comment]
> > @jandres742 any objection to merging this?
> 
> No, but #9 introduced regressions in a test. I'm fixing it and then, once clear, will merge this.
> 
> [intel@592e0d0](https://github.com/intel/llvm/commit/592e0d0589cb4700240f792b9e6d9d387180027e)

branch is back to stable. @bmyates : please rebase.

**Comment by bmyates** [comment]
@jandres742 Rebase complete

**Review by jandres742 — APPROVED** [review]

**Pull request merged**
